# Generated by Django 4.1.5 on 2023-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doner_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dd_username",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="User Name"
                    ),
                ),
                ("dd_email", models.EmailField(max_length=100, verbose_name="Email")),
                ("phone_number", models.IntegerField()),
                (
                    "donation_from",
                    models.CharField(
                        choices=[
                            ("1", "Restaurent"),
                            ("2", "Mess"),
                            ("3", "Hotel"),
                            ("4", "Hostel"),
                            ("5", "Events"),
                            ("6", "Donation"),
                            ("7", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
