# Generated by Django 2.2.19 on 2023-02-15 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='food_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=100)),
                ('pickup_point', models.CharField(max_length=100)),
                ('donar_contact', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date(2023, 2, 15))),
            ],
        ),
        migrations.CreateModel(
            name='Users_donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, verbose_name='Food Name')),
                ('food_type', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('donar_contact', models.CharField(max_length=10)),
                ('food_pick_up', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=6)),
                ('flag', models.CharField(default=False, max_length=2)),
            ],
        ),
    ]
