# Generated by Django 2.2.19 on 2023-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_requests',
            name='flag',
            field=models.CharField(default=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='users_donations',
            name='flag',
            field=models.CharField(default=False, max_length=12),
        ),
    ]
