# Generated by Django 4.1.5 on 2023-02-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users_donations",
            name="username",
            field=models.CharField(default="", max_length=156),
        ),
        migrations.AlterField(
            model_name="users_donations",
            name="flag",
            field=models.CharField(default=False, max_length=12),
        ),
    ]
