# Generated by Django 4.1.5 on 2023-01-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doner_details",
            name="pincode",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
