# Generated by Django 4.1.5 on 2023-01-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_doner_details_pincode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doner_details",
            name="password",
        ),
    ]
