# Generated by Django 4.1.5 on 2023-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_doner_details_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="doner_details",
            name="password",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
